### PR TITLE
Docker update

### PR DESCRIPTION
**Pull request by andrewrech**
@leeprichman also see/check recent commits on main

Could you please try to further reduce the size/complexity of the Docker image, for instance with a different base? Are all of the Ubuntu packages really still required to build?

Please also take for a spin and check if README requires update?

```zsh
# development version not for distribution shared with leeprichman
docker pull andrewrech/antigen.garnish
```

Or:

```zsh
export DOCKER_BUILDKIT=1 BUILDKIT_PROGRESS=plain; docker build .
```

```
[ FAIL 0 | WARN 130 | SKIP 0 | PASS 65 ]
```

### CODE REVIEW

**Comment by andrewrech** [comment]
@leeprichman all tests now pass or are appropriately skipped, have at it

**Review by leeprichman — COMMENTED** [review]
Looks excellent. Continues to improve with each update. Will run tests, update readme, then approve.

**Comment by andrewrech** [comment]
Let's fold in fix for Ian's VCF issue likely due to older SnpEff here also, then you can perhaps also test this with one of your newer VCF files? We should add multiple annotated VCFs to tests

**Comment by leeprichman** [comment]
Ok i will pull once you push that fix to this branch and repeat. will add table input to readme in meantime.

**Comment by andrewrech** [comment]
@leeprichman 

Here it is.

These changes introduced a VCF parsing error outlined below, however I am not yet sure why. Could you help investigate? Currently three tests file in `test-garnish_affinity.R`.

```
Error: dt[, .N, by = pep_type] not equal to `%>%`(...).                   
Different number of rows                                                  
>                                                                         
>     # check unique nmers                                                
>     testthat::expect_true(dt[, nmer %>% unique() %>% length()] == 401)  
Error: dt[, nmer %>% unique() %>% length()] == 401 is not TRUE            
                                                                          
`actual`:   FALSE                                                         
`expected`: TRUE                   

Error in if (check_del_mut[n] != check_del_wt[n]) { :    
  argument is of length zero                             
>                                                        
>     testthat::expect_equal(dif %>% .[1], 1113)         
Error: dif %>% .[1] not equal to 1113.                   
1/1 mismatches                                           
[1] NA - 1113 == NA                                                                       
```

**Comment by andrewrech** [comment]
fixed

**Comment by leeprichman** [comment]
I approve, fixed some paths and minor stuff. If you want me to build and push docker let me know. If you are moving to immunehealth docker hub, README badge and docker instructions need to be updated.

**Review by leeprichman — APPROVED** [review]

**Pull request merged**
